// react-redux-demo/src/components/Home/Home.js
import React, { Component } from 'react'
import axios from 'axios'
import { Link } from 'react-router-dom'
class Home extends Component {
  state = {
    posts: []
  }
  componentDidMount() {
    axios.get('http://localhost:3008/posts').then(res => {
      this.setState({
        posts: res.data
      })
    })
  }

  render() {
    const { posts } = this.state
    const list = posts.length ? (
      <ul>
        {posts.map(e => (
          <li key={e.id}>
            <Link to={`/post/${e.id}`}>{e.title}</Link>
          </li>
        ))}
      </ul>
    ) : (
      <span>请稍等</span>
    )
    return <div>{list}</div>
  }
}

export default Home

// vue-posts/src/components/Home.vue
<template>
  <div>
    <ul v-if="posts.length">
      <li v-for="post in posts" :key="post.id">
        <router-link :to="`/post/${post.id}`">{{post.title}}</router-link>
      </li>
    </ul>
    <div v-else>请稍等。。。</div>
  </div>
</template>
<script>
import axios from "axios";
export default {
  name: "home",
  created() {
    axios.get("http://localhost:3008/posts").then(res => {
      this.posts = res.data;
    });
  },
  data: () => ({
    posts: []
  })
};
</script>
