// vue-juejin/src/components/Post.vue
<template>
  <div v-if="post">
    <h2>{{post.title}}</h2>
    <p>{{post.content}}</p>
  </div>
  <div v-else>稍等片刻</div>
</template>
<script>
import axios from "axios";
export default {
  name: "post",
  created() {
    const { id } = this.$route.params;
    axios.get(`http://localhost:3008/posts/${id}`).then(res => {
      this.post = res.data;
    });
  },
  data: () => ({
    post: null
  })
};
</script>

// react-redux-demo/src/components/Post/Post.js
import React, { Component } from 'react'
import axios from 'axios'

class Post extends Component {
  state = {
    post: null
  }
  componentDidMount() {
    const { id } = this.props.match.params
    axios.get(`http://localhost:3008/posts/${id}`).then(res => {
      this.setState({
        post: res.data
      })
    })
  }

  render() {
    const { post } = this.state
    const article = post ? (
      <article>
        <h2>{post.title}</h2>
        <p>{post.body}</p>
      </article>
    ) : (
      '请稍等'
    )

    return <div>{article}</div>
  }
}

export default Post
